### PR TITLE
Data saturday portugal

### PR DESCRIPTION
**Pull request by WizardDBA**

### CODE REVIEW

**Comment by spaghettidba** [comment]
Hi Ivan, should I merge this PR? Is it closed for a reason?

**Comment by WizardDBA** [comment]
@spaghettidba yes please, sorry getting used to git hub

**Review by spaghettidba — APPROVED** [review]

**Comment by spaghettidba** [comment]
No problem! We should be good now, confirmed?

**Comment by WizardDBA** [comment]
Yup all good thanks for all your support

**Pull request merged**
