### PR TITLE
FutureDataDriven Summit Event

### PR DESCRIPTION
**Pull request by bigdatadriven**
Hello There,

how all is well.

I am currently launching Future Data Driven Summit event on Sep-29-2021 and would love to save the date on DataSaturday.com website. I will provide all other information in two weeks. All I am asking now is to post the event name and date on the website in order to save the date.

Call for speakers link: https://sessionize.com/FutureDataDriven

Best Regards,
Jean Joseph

### CODE REVIEW

**Comment by spaghettidba** [comment]
Jean, this PR touches each and every file in the repository. I don't even know how this is possible, however this doesn't look good.
If you want to reserve a date for an event, please drop me an email with the information required and I will create the PR for you

**Comment by bigdatadriven** [comment]
Hello Gianluca,

Thanks again for your support.

please find below event details

*Event name:* Future Data Driven.
*Date:* Sep-29-2021

**Comment by bigdatadriven** [comment]
*Event name:* Future Data Driven Summit.

**Comment by bigdatadriven** [comment]
I also have its logo and can be found here:
https://github.com/bigdatadriven/FutureDataDriven/blob/main/FDD_logo.PNG

**Pull request closed without merging**
