### PR TITLE
Update index.html (events in chronological order)

### PR DESCRIPTION
**Pull request by HugoKornelis**
Events are currently listed in order of creation. It's easier to have them in chronological order. Since the event list is currently hardcoded, I changed their order and hope that in the future, when events are added or rescheduled, they are put in the correct location within the list.

I assume the list will in the future be dynamically generated from a database. But until then, this will be a manual process.

Note that this PR addresses issue #87

### CODE REVIEW

**Comment by spaghettidba** [comment]
Hi Hugo and thanks for contributing to DataSaturdays. 
See my reply to #87 : this is going to be addressed in code.
I would vote to close this PR fot the time being, but I'm open to everyone's feedback if you feel the discussion is not closed yet.

**Comment by HugoKornelis** [comment]
My PR was intended to be a stopgap measure to at least have the list sorted by date now.
But if you prefer to keep the list as is now and wait for the permanent solution, that's fine with me too. It's not relevant enough to spend more of my time on now.

**Comment by amtwo** [comment]
I would be in favor of having the static/manually-maintained list sorted by date as the default, until the dynamic & sortable list is ready to go.

**Comment by spaghettidba** [comment]
Dynamic sorting almost ready, hold on folks :)

**Comment by amtwo** [comment]
Well, if @spaghettidba is almost done with the long-term solution, then I guess the whole conversation is moot. 💃

**Comment by way0utwest** [comment]
I have merged the PR from @spaghettidba that allows dynamic sorting. Thanks, @HugoKornelis , but closing this as it's not needed.

**Pull request closed without merging**
