### PR TITLE
Croatia

### PR DESCRIPTION
**Pull request by matesic-damir**

### CODE REVIEW

**Comment by matesic-damir** [comment]
Added sponsors for Croatia Event. Please approve

**Comment by spaghettidba** [comment]
Hi Damir! It looks like you added the ".vs" folder. Can you please remove it? Just delete the folder and commit + push on this same branch.
Thanks!

**Comment by matesic-damir** [comment]
Hello, 

i did delete it.

Thanks,
Damir
On 1.4.2021. 14:41:11, Gianluca Sartori ***@***.***> wrote:
Hi Damir! It looks like you added the ".vs" folder. Can you please remove it? Just delete the folder and commit + push on this same branch.
Thanks!

**Comment by matesic-damir** [comment]
.gitignore added and .vs removed. Can you check now

**Review by spaghettidba — APPROVED** [review]

**Comment by spaghettidba** [comment]
Inclusive language warning refers to a comment in .gitignore so it should be fine

**Pull request merged**
