### PR TITLE
Correct the font name 

### PR DESCRIPTION
**Pull request by amtwo**
Oops, It's "Roboto Slab" not "Roboto"

Also add URLs to the Google Font examples

### CODE REVIEW

**Comment by amtwo** [comment]
@SQLDBAWithABeard I know you _just_ added this accessibility check, but I'm not sure what the failure error means:
> Error: Resource not accessible by integration

**Comment by LowlyDBA** [comment]
Seems like perhaps a flake, since it ran correctly on your subsequent comment. We probably don't need that work flow set as a required check on PRs given the nature of it

**Comment by SQLDBAWithABeard** [comment]
I don’t know why it’s running that one 😞

**Comment by SQLDBAWithABeard** [comment]
Ha, I fixed though. I do know why it seems!

**Review by SQLDBAWithABeard — APPROVED** [review]
Thank you Andy

**Pull request merged**
