### PR TITLE
updating details of event

### PR DESCRIPTION
**Pull request by kramer1007**
Just setting up some more details for our event upcoming next month. If you see any mistakes or issues, let me know. Thanks.

### CODE REVIEW

**Review by SQLDBAWithABeard — APPROVED** [review]

**Comment by kramer1007** [comment]
@SQLDBAWithABeard  does something have to be done for the main page to reflect the changes made in the data?

**Comment by spaghettidba** [comment]
It looks like the page fails to build. I have no idea why, it's probably something wrong with the yml but I don't know what. Does it build locally?

**Comment by spaghettidba** [comment]
@SQLDBAWithABeard The yml file looks ok to me, but it fails to build. Any ideas?

**Comment by kramer1007** [comment]
Looks like Gianluca got it fixed up. Thanks!

-Chris

**Pull request closed without merging**
